[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "ctf_core"
dynamic = ["version"]
requires-python = ">=3.10"

[tool.maturin]
bindings = "pyo3-abi3"
module-name = "maze_core._core"
python-source = "python"
