# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from enum import Enum

class Action:
    class Move(Action):
        __match_args__ = ("agent_id", "velocity",)
        @property
        def agent_id(self) -> builtins.int: ...
        @property
        def velocity(self) -> tuple[builtins.float, builtins.float]: ...
        def __new__(cls, agent_id:builtins.int, velocity:tuple[builtins.float, builtins.float]) -> Action.Move: ...
    
    class PickupFlag(Action):
        __match_args__ = ("agent_id",)
        @property
        def agent_id(self) -> builtins.int: ...
        def __new__(cls, agent_id:builtins.int) -> Action.PickupFlag: ...
    
    class DropFlag(Action):
        __match_args__ = ("agent_id",)
        @property
        def agent_id(self) -> builtins.int: ...
        def __new__(cls, agent_id:builtins.int) -> Action.DropFlag: ...
    
    ...

class AgentConfig:
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None: ...
    @property
    def max_speed(self) -> builtins.float: ...
    @max_speed.setter
    def max_speed(self, value: builtins.float) -> None: ...
    @property
    def policy_hz(self) -> builtins.float: ...
    @policy_hz.setter
    def policy_hz(self, value: builtins.float) -> None: ...
    @property
    def position_stddev(self) -> builtins.float: ...
    @position_stddev.setter
    def position_stddev(self, value: builtins.float) -> None: ...
    @property
    def range_stddev(self) -> builtins.float: ...
    @range_stddev.setter
    def range_stddev(self, value: builtins.float) -> None: ...
    @property
    def occupancy_grid_cell_size(self) -> builtins.float: ...
    @occupancy_grid_cell_size.setter
    def occupancy_grid_cell_size(self, value: builtins.float) -> None: ...

class AgentState:
    @property
    def id(self) -> builtins.int:
        r"""
        The unique ID of the agent entity.
        """
    @property
    def position(self) -> tuple[builtins.float, builtins.float]:
        r"""
        The (noisy!) position of the agent in world coordinates
        """
    @property
    def position_stddev(self) -> builtins.float:
        r"""
        The standard deviation of the position noise. This noise is Gaussian with mean 0 and stddev `position_stddev`.
        """
    @property
    def raycasts(self) -> builtins.list[HitInfo]:
        r"""
        The results of the agent's raycasts.
        """
    @property
    def flag_id(self) -> typing.Optional[builtins.int]:
        r"""
        The entity ID of the flag the agent is currently carrying, if any.
        """
    @property
    def max_speed(self) -> builtins.float:
        r"""
        The maximum linear speed of the agent.
        """

class FlagConfig:
    @property
    def flag_count(self) -> builtins.int: ...
    @flag_count.setter
    def flag_count(self, value: builtins.int) -> None: ...
    @property
    def capture_point_count(self) -> builtins.int: ...
    @capture_point_count.setter
    def capture_point_count(self, value: builtins.int) -> None: ...

class GameResult:
    r"""
    The outcome of a headless run.
    """
    @property
    def elapsed_seconds(self) -> builtins.float:
        r"""
        Simulated seconds elapsed when the run stopped.
        """
    @property
    def timed_out(self) -> builtins.bool:
        r"""
        True if the run stopped because it hit the time limit rather than finishing early.
        """
    @property
    def final_mapping_error(self) -> builtins.float:
        r"""
        Fraction of ground-truth cells the agent's map got wrong, in `[0, 1]`.
        """
    @property
    def mapping_error_cells(self) -> tuple[builtins.int, builtins.int]:
        r"""
        `(wrong, total)` cell counts behind `final_mapping_error`.
        """
    @property
    def mapping_error_milestones(self) -> builtins.list[tuple[builtins.float, typing.Optional[builtins.float]]]:
        r"""
        For each requested threshold, the first simulated time the mapping error dropped to or
        below it, or `None` if it never did. In the order the thresholds were given.
        """
    @property
    def flag_capture_times(self) -> builtins.list[builtins.float]:
        r"""
        Simulated time of each flag capture, in order.
        """
    @property
    def flags_captured(self) -> builtins.int: ...
    @property
    def total_flags(self) -> builtins.int: ...
    @property
    def maze_seed(self) -> builtins.int:
        r"""
        The maze seed actually used. Worth recording when the config left `seed` unset, since it is
        what makes a run reproducible.
        """
    @property
    def policy_error(self) -> typing.Optional[builtins.str]:
        r"""
        Set if the Python policy raised or stopped responding, in which case the run ended early
        and the other metrics describe only the part that ran.
        """
    def __str__(self) -> builtins.str: ...
    def time_to_mapping_error(self, threshold:builtins.float) -> typing.Optional[builtins.float]:
        r"""
        The first simulated time the mapping error reached `threshold`, or `None` if it never did.
        Only thresholds that were requested for the run are known.
        """
    def __repr__(self) -> builtins.str: ...

class GameState:
    @property
    def agent(self) -> AgentState: ...
    @property
    def total_flags(self) -> builtins.int: ...
    @property
    def captured_flags(self) -> builtins.int: ...
    @property
    def world_width(self) -> builtins.float: ...
    @property
    def world_height(self) -> builtins.float: ...

class HitInfo:
    @property
    def theta(self) -> builtins.float:
        r"""
        The angle of the raycast in radians, relative to the +x axis (right on the screen). Remember, +y points down on the screen!
        """
    @property
    def endpoint_type(self) -> EntityType:
        r"""
        The type of entity that was hit by the raycast.
        """
    @property
    def distance(self) -> builtins.float:
        r"""
        How far the ray traveled before hitting something, or the max distance if nothing was hit.
        """
    @property
    def max_distance(self) -> builtins.float:
        r"""
        The maximum distance the raycast could travel.
        """
    @property
    def endpoint_confidence(self) -> SensorConfidence:
        r"""
        The confidence (probability of each class) of the thing that the ray hit.
        If nothing was hit, this will be the confidence of an empty space.
        """
    @property
    def free_confidence(self) -> SensorConfidence:
        r"""
        The confidence (probability of each class) of the cells that the ray passed through of being free space.
        """
    def __str__(self) -> builtins.str: ...

class MazeConfig:
    @property
    def agent(self) -> AgentConfig: ...
    @agent.setter
    def agent(self, value: AgentConfig) -> None: ...
    @property
    def flags(self) -> FlagConfig: ...
    @flags.setter
    def flags(self, value: FlagConfig) -> None: ...
    @property
    def maze_generation(self) -> MazeGenerationConfig: ...
    @maze_generation.setter
    def maze_generation(self, value: MazeGenerationConfig) -> None: ...
    @property
    def use_true_map(self) -> builtins.bool: ...
    @use_true_map.setter
    def use_true_map(self, value: builtins.bool) -> None: ...
    @property
    def teleop(self) -> builtins.bool:
        r"""
        When true the agent is driven by the keyboard: `Arrows` or `WASD` to move, `Space` to pick
        up and drop flags. The Python policy still runs every tick so a mapping agent keeps building
        its occupancy grid while you drive, but its actions are ignored.
        """
    @teleop.setter
    def teleop(self, value: builtins.bool) -> None:
        r"""
        When true the agent is driven by the keyboard: `Arrows` or `WASD` to move, `Space` to pick
        up and drop flags. The Python policy still runs every tick so a mapping agent keeps building
        its occupancy grid while you drive, but its actions are ignored.
        """
    @property
    def debug(self) -> builtins.bool: ...
    @debug.setter
    def debug(self, value: builtins.bool) -> None: ...
    @property
    def headless(self) -> builtins.bool: ...
    @headless.setter
    def headless(self, value: builtins.bool) -> None: ...

class MazeGenerationConfig:
    @property
    def seed(self) -> typing.Optional[builtins.int]: ...
    @seed.setter
    def seed(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def world_width(self) -> builtins.float: ...
    @world_width.setter
    def world_width(self, value: builtins.float) -> None: ...
    @property
    def world_height(self) -> builtins.float: ...
    @world_height.setter
    def world_height(self, value: builtins.float) -> None: ...
    @property
    def cell_size(self) -> builtins.float: ...
    @cell_size.setter
    def cell_size(self, value: builtins.float) -> None: ...

class OccupancyGrid:
    @property
    def cell_size(self) -> builtins.float:
        r"""
        Size of each cell in world units
        """
    @property
    def columns(self) -> builtins.int:
        r"""
        Number of columns
        """
    @property
    def rows(self) -> builtins.int:
        r"""
        Number of rows
        """
    @property
    def shape(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Returns (columns, rows)
        """
    def __new__(cls, columns:builtins.int, rows:builtins.int, cell_size:builtins.float) -> OccupancyGrid: ...
    def __getitem__(self, key:typing.Any) -> OccupancyGridEntry: ...

class OccupancyGridEntry:
    @property
    def assignment(self) -> typing.Optional[EntityType]:
        r"""
        The assignment of the cell, or None if unassigned. Must be manually set
        """
    @assignment.setter
    def assignment(self, value: typing.Optional[EntityType]) -> None: ...
    @property
    def logit_free(self) -> builtins.float:
        r"""
        The logit value for the "free" class. Higher means more likely to be free. Clamped to [-LOGIT_CLAMP, LOGIT_CLAMP]
        """
    @logit_free.setter
    def logit_free(self, value: builtins.float) -> None: ...
    @property
    def logit_wall(self) -> builtins.float:
        r"""
        The logit value for the "wall" class. Higher means more likely to be wall. Clamped to [-LOGIT_CLAMP, LOGIT_CLAMP]
        """
    @logit_wall.setter
    def logit_wall(self, value: builtins.float) -> None: ...
    @property
    def logit_flag(self) -> builtins.float:
        r"""
        The logit value for the "flag" class. Higher means more likely to be flag. Clamped to [-LOGIT_CLAMP, LOGIT_CLAMP]
        """
    @logit_flag.setter
    def logit_flag(self, value: builtins.float) -> None: ...
    @property
    def logit_capture_point(self) -> builtins.float:
        r"""
        The logit value for the "capture_point" class. Higher means more likely to be capture_point. Clamped to [-LOGIT_CLAMP, LOGIT_CLAMP]
        """
    @logit_capture_point.setter
    def logit_capture_point(self, value: builtins.float) -> None: ...
    def __str__(self) -> builtins.str: ...
    def probabilities(self) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float]:
        r"""
        Returns the probabilities of each class as a tuple (p_free, p_wall, p_flag, p_capture_point) using a softmax over the logits.
        """

class OccupancyGridView:
    @property
    def cell_size(self) -> builtins.float: ...
    @property
    def columns(self) -> builtins.int: ...
    @property
    def rows(self) -> builtins.int: ...
    @property
    def shape(self) -> tuple[builtins.int, builtins.int]: ...
    def __getitem__(self, key:typing.Any) -> OccupancyGridEntry: ...

class SensorConfidence:
    @property
    def conf_free(self) -> builtins.float:
        r"""
        Confidence in free space
        """
    @property
    def conf_wall(self) -> builtins.float:
        r"""
        Confidence in a wall
        """
    @property
    def conf_flag(self) -> builtins.float:
        r"""
        Confidence in a flag
        """
    @property
    def conf_capture_point(self) -> builtins.float:
        r"""
        Confidence in a capture point
        """
    def __new__(cls, conf_free:builtins.float, conf_wall:builtins.float, conf_flag:builtins.float, conf_capture_point:builtins.float) -> SensorConfidence: ...
    def as_tuple(self) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float]: ...

class StateQueue:
    @property
    def rate_hz(self) -> builtins.float: ...
    def get(self, timeout_ms:typing.Optional[builtins.int]) -> typing.Optional[tuple[GameState, OccupancyGridView, OccupancyGridView]]:
        r"""
        Wait for next GameState (timeout ms optional). Returns None on timeout.
        """
    def stop(self) -> None:
        r"""
        Ask the sim to stop.
        """
    def join(self) -> None:
        r"""
        Join the sim thread.
        """

class EntityType(Enum):
    r"""
    The type of entity that was hit by a raycast. Note, that "Unknown" should not occur.
    """
    Free = ...
    Wall = ...
    Flag = ...
    CapturePoint = ...
    Unknown = ...

def parse_config(config_path:builtins.str) -> MazeConfig: ...

def run(config:MazeConfig, policy:typing.Any) -> typing.Optional[StateQueue]: ...

def run_headless(config:MazeConfig, policy:typing.Any, max_seconds:builtins.float=300.0, mapping_error_milestones:typing.Sequence[builtins.float]=[0.800000011920929, 0.6000000238418579, 0.4000000059604645, 0.20000000298023224], stop_on_all_flags_captured:builtins.bool=False) -> GameResult:
    r"""
    Play a whole game with no window, as fast as the policy can be evaluated, and return what
    happened.
    
    The clock is simulated: `max_seconds` counts simulated seconds, so a 300-second budget matches
    the assignment's five-minute target regardless of how long the run actually takes. Every
    simulated tick calls `get_action` exactly once — the sim waits for the policy rather than
    skipping ahead — so a run is reproducible for a given maze seed.
    """

