# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from enum import Enum

class Action:
    r"""
    An action returned by an agent policy.
    """
    class Move(Action):
        r"""
        Moves agent `agent_id` at `velocity`, capped to agent's max speed.
        Example: `Action.Move(agent_id, velocity)`.
        """
        __match_args__ = ("agent_id", "velocity",)
        @property
        def agent_id(self) -> builtins.int: ...
        @property
        def velocity(self) -> tuple[builtins.float, builtins.float]: ...
        def __new__(cls, agent_id:builtins.int, velocity:tuple[builtins.float, builtins.float]) -> Action.Move: ...
    
    class PickupFlag(Action):
        r"""
        Makes agent `agent_id` attempt to pick up a nearby flag.
        Example: `Action.PickupFlag(agent_id)`.
        """
        __match_args__ = ("agent_id",)
        @property
        def agent_id(self) -> builtins.int: ...
        def __new__(cls, agent_id:builtins.int) -> Action.PickupFlag: ...
    
    class DropFlag(Action):
        r"""
        Makes agent `agent_id` attempt to drop its flag at a capture point.
        Example: `Action.DropFlag(agent_id)`.
        """
        __match_args__ = ("agent_id",)
        @property
        def agent_id(self) -> builtins.int: ...
        def __new__(cls, agent_id:builtins.int) -> Action.DropFlag: ...
    
    ...

class AgentConfig:
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None: ...
    @property
    def max_speed(self) -> builtins.float: ...
    @max_speed.setter
    def max_speed(self, value: builtins.float) -> None: ...
    @property
    def policy_hz(self) -> builtins.float:
        r"""
        How often `get_action` is called, in Hz. Zero disables the policy entirely, which is only
        useful for a keyboard-only teleop demonstration.
        """
    @policy_hz.setter
    def policy_hz(self, value: builtins.float) -> None:
        r"""
        How often `get_action` is called, in Hz. Zero disables the policy entirely, which is only
        useful for a keyboard-only teleop demonstration.
        """
    @property
    def position_stddev(self) -> builtins.float: ...
    @position_stddev.setter
    def position_stddev(self, value: builtins.float) -> None: ...
    @property
    def range_stddev(self) -> builtins.float: ...
    @range_stddev.setter
    def range_stddev(self, value: builtins.float) -> None: ...
    @property
    def occupancy_grid_cell_size(self) -> builtins.float: ...
    @occupancy_grid_cell_size.setter
    def occupancy_grid_cell_size(self, value: builtins.float) -> None: ...
    @property
    def policy_timeout_seconds(self) -> builtins.float:
        r"""
        How long the simulation waits for one `get_action` call before giving up on the policy, in
        seconds. Zero waits forever, which is what a debugger session needs.
        """
    @policy_timeout_seconds.setter
    def policy_timeout_seconds(self, value: builtins.float) -> None:
        r"""
        How long the simulation waits for one `get_action` call before giving up on the policy, in
        seconds. Zero waits forever, which is what a debugger session needs.
        """

class AgentState:
    r"""
    Represents the state of the agent, including its observed information.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Returns the entity ID of the agent.
        """
    @property
    def position(self) -> tuple[builtins.float, builtins.float]:
        r"""
        Returns the observed position, including position noise.
        """
    @property
    def position_stddev(self) -> builtins.float:
        r"""
        Returns the standard deviation of position observations.
        """
    @property
    def raycasts(self) -> builtins.list[HitInfo]:
        r"""
        Returns a list of range-sensor readings.
        """
    @property
    def flag_id(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the ID of the flag carried, if any.
        """
    @property
    def max_speed(self) -> builtins.float:
        r"""
        Returns the maximum linear speed of the agent.
        """

class FlagConfig:
    @property
    def flag_count(self) -> builtins.int: ...
    @flag_count.setter
    def flag_count(self, value: builtins.int) -> None: ...
    @property
    def capture_point_count(self) -> builtins.int: ...
    @capture_point_count.setter
    def capture_point_count(self, value: builtins.int) -> None: ...

class GameResult:
    r"""
    The outcome of a headless run.
    """
    @property
    def elapsed_seconds(self) -> builtins.float:
        r"""
        Simulated seconds elapsed when the run stopped.
        """
    @property
    def timed_out(self) -> builtins.bool:
        r"""
        True if the run stopped because it hit the time limit rather than finishing early.
        """
    @property
    def final_mapping_accuracy(self) -> builtins.float:
        r"""
        Fraction of ground-truth cells the agent's map classified correctly, in `[0, 1]`.
        """
    @property
    def mapping_accuracy_cells(self) -> tuple[builtins.int, builtins.int]:
        r"""
        `(correct, total)` cell counts behind `final_mapping_accuracy`.
        """
    @property
    def final_free_recall(self) -> builtins.float:
        r"""
        Fraction of true free space cells classified as free, in `[0, 1]`.
        """
    @property
    def free_recall_cells(self) -> tuple[builtins.int, builtins.int]:
        r"""
        `(correct, total)` free space cell counts behind `final_free_recall`.
        """
    @property
    def final_wall_recall(self) -> builtins.float:
        r"""
        Fraction of true wall cells classified as walls, in `[0, 1]`.
        """
    @property
    def wall_recall_cells(self) -> tuple[builtins.int, builtins.int]:
        r"""
        `(correct, total)` wall cell counts behind `final_wall_recall`.
        """
    @property
    def mapping_accuracy_milestones(self) -> builtins.list[tuple[builtins.float, typing.Optional[builtins.float]]]:
        r"""
        For each requested threshold, the first simulated time mapping accuracy reached or
        exceeded it, or `None` if it never did. In the order the thresholds were given.
        """
    @property
    def flag_capture_times(self) -> builtins.list[builtins.float]:
        r"""
        Simulated time of each flag capture, in order.
        """
    @property
    def flags_captured(self) -> builtins.int: ...
    @property
    def total_flags(self) -> builtins.int: ...
    @property
    def capturable_flags(self) -> builtins.int:
        r"""
        The most flags this configuration can ever have captured. A capture point holds a single
        flag, so a run with more flags than capture points cannot reach `total_flags`.
        """
    @property
    def maze_seed(self) -> builtins.int:
        r"""
        The maze seed actually used. Worth recording when the config left `seed` unset, since it is
        what makes a run reproducible.
        """
    @property
    def policy_error(self) -> typing.Optional[builtins.str]:
        r"""
        Set if the Python policy raised or stopped responding, in which case the run ended early
        and the other metrics describe only the part that ran.
        """
    def __str__(self) -> builtins.str: ...
    def time_to_mapping_accuracy(self, threshold:builtins.float) -> typing.Optional[builtins.float]:
        r"""
        The first simulated time mapping accuracy reached `threshold`, or `None` if it never did.
        Only thresholds that were requested for the run are known.
        """
    def __repr__(self) -> builtins.str: ...

class GameState:
    r"""
    Represents a snapshot of the game state.
    """
    @property
    def agent(self) -> AgentState:
        r"""
        Returns the state of the agent.
        """
    @property
    def total_flags(self) -> builtins.int:
        r"""
        Returns the total number of flags.
        """
    @property
    def captured_flags(self) -> builtins.int:
        r"""
        Returns the number of flags delivered to capture points.
        """
    @property
    def world_width(self) -> builtins.float: ...
    @property
    def world_height(self) -> builtins.float: ...

class HitInfo:
    r"""
    Represents one range-sensor reading from the agent's current position.
    """
    @property
    def theta(self) -> builtins.float:
        r"""
        Returns the ray angle in radians clockwise from +x.
        """
    @property
    def endpoint_type(self) -> EntityType:
        r"""
        Returns the type observed at the raycast endpoint. Equals `Free` if
        no collision occurs before the endpoint.
        """
    @property
    def distance(self) -> builtins.float:
        r"""
        Returns the reported distance, including range noise.
        """
    @property
    def max_distance(self) -> builtins.float:
        r"""
        Returns the maximum distance the raycast can travel.
        """
    @property
    def endpoint_confidence(self) -> SensorConfidence:
        r"""
        Returns the per-class confidence at the endpoint.
        """
    @property
    def free_confidence(self) -> SensorConfidence:
        r"""
        Returns the per-class confidence for cells before the endpoint.
        """
    def __str__(self) -> builtins.str: ...

class MazeConfig:
    @property
    def agent(self) -> AgentConfig: ...
    @agent.setter
    def agent(self, value: AgentConfig) -> None: ...
    @property
    def flags(self) -> FlagConfig: ...
    @flags.setter
    def flags(self, value: FlagConfig) -> None: ...
    @property
    def maze_generation(self) -> MazeGenerationConfig: ...
    @maze_generation.setter
    def maze_generation(self, value: MazeGenerationConfig) -> None: ...
    @property
    def use_true_map(self) -> builtins.bool: ...
    @use_true_map.setter
    def use_true_map(self, value: builtins.bool) -> None: ...
    @property
    def debug(self) -> builtins.bool: ...
    @debug.setter
    def debug(self, value: builtins.bool) -> None: ...
    @property
    def headless(self) -> builtins.bool: ...
    @headless.setter
    def headless(self, value: builtins.bool) -> None: ...
    @property
    def teleop(self) -> builtins.bool:
        r"""
        Drive the agent from the keyboard: `Arrows` or `WASD` to move, `Space` to pick up and drop
        flags. The policy is still queried, so a mapping agent keeps building its occupancy grid
        while you drive, but its actions are ignored. To skip the policy entirely — a teleop
        demonstration with an agent that is not written yet — set `agent.policy_hz` to zero in the
        config file.
        """
    @teleop.setter
    def teleop(self, value: builtins.bool) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

class MazeGenerationConfig:
    @property
    def seed(self) -> typing.Optional[builtins.int]: ...
    @seed.setter
    def seed(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def world_width(self) -> builtins.float: ...
    @world_width.setter
    def world_width(self, value: builtins.float) -> None: ...
    @property
    def world_height(self) -> builtins.float: ...
    @world_height.setter
    def world_height(self, value: builtins.float) -> None: ...
    @property
    def cell_size(self) -> builtins.float: ...
    @cell_size.setter
    def cell_size(self, value: builtins.float) -> None: ...

class OccupancyGrid:
    r"""
    Represents a mutable occupancy grid, indexed by `grid[column, row]`.
    """
    @property
    def cell_size(self) -> builtins.float:
        r"""
        Returns the edge length of each cell.
        """
    @property
    def columns(self) -> builtins.int:
        r"""
        Returns the number of columns.
        """
    @property
    def rows(self) -> builtins.int:
        r"""
        Returns the number of rows.
        """
    @property
    def shape(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Returns `(columns, rows)`.
        """
    def __new__(cls, columns:builtins.int, rows:builtins.int, cell_size:builtins.float) -> OccupancyGrid: ...
    def __getitem__(self, key:typing.Any) -> OccupancyGridEntry: ...

class OccupancyGridEntry:
    r"""
    Represents a mutable occupancy-grid cell.
    """
    @property
    def assignment(self) -> typing.Optional[EntityType]:
        r"""
        Mutable cell type assignment. Must be updated manually.
        """
    @assignment.setter
    def assignment(self, value: typing.Optional[EntityType]) -> None: ...
    @property
    def logit_free(self) -> builtins.float:
        r"""
        Mutable logit for free space.
        """
    @logit_free.setter
    def logit_free(self, value: builtins.float) -> None: ...
    @property
    def logit_wall(self) -> builtins.float:
        r"""
        Mutable logit for a wall.
        """
    @logit_wall.setter
    def logit_wall(self, value: builtins.float) -> None: ...
    @property
    def logit_flag(self) -> builtins.float:
        r"""
        Mutable logit for a flag.
        """
    @logit_flag.setter
    def logit_flag(self, value: builtins.float) -> None: ...
    @property
    def logit_capture_point(self) -> builtins.float:
        r"""
        Mutable logit for a capture point.
        """
    @logit_capture_point.setter
    def logit_capture_point(self, value: builtins.float) -> None: ...
    def __str__(self) -> builtins.str: ...
    def probabilities(self) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float]:
        r"""
        Returns softmax probabilities `(free, wall, flag, capture_point)`.
        """

class OccupancyGridView:
    @property
    def cell_size(self) -> builtins.float: ...
    @property
    def columns(self) -> builtins.int: ...
    @property
    def rows(self) -> builtins.int: ...
    @property
    def shape(self) -> tuple[builtins.int, builtins.int]: ...
    def __getitem__(self, key:typing.Any) -> OccupancyGridEntry: ...

class SensorConfidence:
    r"""
    Represents per-class sensor confidence used to update an occupancy grid.
    Note that these are not normalized probabilities.
    """
    @property
    def conf_free(self) -> builtins.float:
        r"""
        Returns the confidence in a free space.
        """
    @property
    def conf_wall(self) -> builtins.float:
        r"""
        Returns the confidence in a wall.
        """
    @property
    def conf_flag(self) -> builtins.float:
        r"""
        Returns the confidence in a flag.
        """
    @property
    def conf_capture_point(self) -> builtins.float:
        r"""
        Returns the confidence in a capture point.
        """
    def __new__(cls, conf_free:builtins.float, conf_wall:builtins.float, conf_flag:builtins.float, conf_capture_point:builtins.float) -> SensorConfidence: ...
    def as_tuple(self) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float]:
        r"""
        Returns `(conf_free, conf_wall, conf_flag, conf_capture_point)`.
        """

class StateQueue:
    @property
    def rate_hz(self) -> builtins.float: ...
    def get(self, timeout_ms:typing.Optional[builtins.int]) -> typing.Optional[tuple[GameState, OccupancyGridView, OccupancyGridView]]:
        r"""
        Wait for next GameState (timeout ms optional). Returns None on timeout.
        """
    def stop(self) -> None:
        r"""
        Ask the sim to stop.
        """
    def join(self) -> None:
        r"""
        Join the sim thread.
        """

class EntityType(Enum):
    r"""
    Represents the type observed at the endpoint of a range-sensor reading.
    """
    Free = ...
    Wall = ...
    Flag = ...
    CapturePoint = ...
    Unknown = ...

def parse_config(config_path:builtins.str) -> MazeConfig: ...

def run(config:MazeConfig, policy:typing.Any) -> typing.Optional[StateQueue]: ...

def run_headless(config:MazeConfig, policy:typing.Any, max_seconds:builtins.float=300.0, mapping_accuracy_milestones:typing.Sequence[builtins.float]=[0.20000000298023224, 0.4000000059604645, 0.6000000238418579, 0.800000011920929], stop_on_all_flags_captured:builtins.bool=False) -> GameResult:
    r"""
    Play a whole game with no window, as fast as the policy can be evaluated, and return what
    happened.
    
    The clock is simulated: `max_seconds` counts simulated seconds, so a 300-second budget matches
    the assignment's five-minute target regardless of how long the run actually takes. The
    simulation waits for each `get_action` to return rather than skipping ahead, so a run is
    reproducible for a given maze seed.
    """

